version: "3.9"
services:
  dev-db:
    image: postgres:16.3
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: icodeu

  # app:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
